/**
 * scaffold.ts — initialize a vault with the LLM Wiki layout.
 *
 * Default template scaffolds: wiki/, .raw/, wiki/meta/, plus seed files
 * (index.md, hot.md, log.md, Inbox.md). Dry-run by default; pass
 * `{ apply: true }` to actually write.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { resolveLayout, type PluginConfig } from './vault.js';

export interface ScaffoldArgs {
  template?: 'default' | 'minimal' | 'research';
  apply?: boolean;
}

export interface ScaffoldPlan {
  create: string[];
  write: { path: string; content: string }[];
  skipped: string[];
}

export function plan(vaultPath: string, config: PluginConfig, args: ScaffoldArgs = {}): ScaffoldPlan {
  const layout = resolveLayout(vaultPath, config);
  const plan: ScaffoldPlan = { create: [], write: [], skipped: [] };

  // dirs
  for (const d of [
    layout.wikiDir,
    layout.rawDir,
    layout.metaDir,
    join(layout.wikiDir, 'areas'),
    join(layout.wikiDir, 'projects'),
    join(layout.wikiDir, 'resources'),
    join(layout.wikiDir, 'sources'),
    join(layout.wikiDir, 'archive'),
    join(vaultPath, 'inbox'),
  ]) {
    if (existsSync(d)) plan.skipped.push(d);
    else plan.create.push(d);
  }

  // files
  if (!existsSync(layout.indexFile)) {
    plan.write.push({ path: layout.indexFile, content: '# Index\n\n## Areas\n\n## Projects\n\n## Resources\n\n## Sources\n\n' });
  }
  if (!existsSync(layout.hotFile)) {
    plan.write.push({ path: layout.hotFile, content: '# Hot Cache\n\n_Recent context, regenerated by `wiki_query` quick mode._\n' });
  }
  if (!existsSync(layout.logFile)) {
    plan.write.push({ path: layout.logFile, content: '# Log\n\n' });
  }
  if (!existsSync(join(vaultPath, 'inbox', 'Inbox.md'))) {
    plan.write.push({
      path: join(vaultPath, 'inbox', 'Inbox.md'),
      content: '# Inbox\n\nDrop source URLs, file paths, or paste raw notes here. The `wiki-ingest` skill processes them into the vault.\n',
    });
  }

  if (args.template === 'research') {
    plan.write.push({
      path: join(layout.wikiDir, 'Research Questions.md'),
      content: '# Research Questions\n\n- [ ] \n',
    });
  }

  return plan;
}

export function scaffold(vaultPath: string, config: PluginConfig, args: ScaffoldArgs = {}): ScaffoldPlan | { applied: true; plan: ScaffoldPlan } {
  const p = plan(vaultPath, config, args);
  if (!args.apply) return p;

  for (const d of p.create) mkdirSync(d, { recursive: true });
  for (const f of p.write) {
    mkdirSync(join(f.path, '..'), { recursive: true }); // no-op for files, but safe
    writeFileSync(f.path, f.content, 'utf8');
  }
  return { applied: true, plan: p };
}
